import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import {Poppins} from "next/font/google"

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";
import { Providers } from "~/providers/providers";
import { AppProps } from "next/app";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const poppins = Poppins({
  weight: ["400","600"],
  subsets: ["latin"],


})
 
export default function RootLayout({
  children,
  pageProps
}: {
  children: React.ReactNode;
  pageProps:AppProps["pageProps"]
}) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <head><title>Emailify</title>
      
      </head>
      

      <body>
        <Providers pageProps={pageProps}>
        <TRPCReactProvider>{children}</TRPCReactProvider>

        </Providers>
      </body>
    </html>
  );
}
